### ISSUE TITLE
Make the text snippets consistent.

### ISSUE THREAD

**Issue by morsapaes** [sorahn/flink-ecosystem#39]
The text snippets supporting input fields are a bit inconstintent. For example:

     "Supported image types: gif/png/jpg"

     "Supports Github Flavored Markdown."

Aside from improving this, I would also suggest to:

**1.** Add some kind of "context" to the main webpage, letting users know the purpose of the website.

**2.** Change the achor text to the website from "Apache Flink" to "Apache Flink Website".

**Comment by rmetzger** [comment]
Good point to add some context!

I guess is a good area to put it:
<img width="1136" alt="Screenshot 2019-07-12 12 46 04" src="https://user-images.githubusercontent.com/89049/61122794-06125500-a4a3-11e9-9d23-5b86e8e06b4c.png">

Do you want to propose a text @morsapaes?
