### ISSUE TITLE
Add "context" to the main page.

### ISSUE THREAD

**Issue by sorahn** [sorahn/flink-ecosystem#46]
From #39 

>1. Add some kind of "context" to the main webpage, letting users know the purpose of the website.

@rmetzger plz help.

**Comment by rmetzger** [comment]
------------------------------------

### This page contains third-party projects around Apache Flink

Users can explore the Flink ecosystem of connectors, extensions, APIs, tool and integrations here.
Developers in the ecosystem can submit what they have build as a new packages.
Comments and votes allow users leave feedback, get help and assess the quality of a community package.
**Note:** Packages listed here are user-submitted, they are not not endorsed by the Apache Flink project.

------------------------------------



What do you think @morsapaes @sorahn ?

**Comment by sorahn** [comment]
fixed in #66
