### ISSUE TITLE
Mark required field with a "*" symbol

### ISSUE THREAD

**Issue by klion26** [sorahn/flink-ecosystem#57]
![image](https://user-images.githubusercontent.com/1425623/61424424-06e53400-a946-11e9-8991-fcd6835c67b4.png)

Can we mark the required filed such as (repository, license, category, etc.) with a "*" label, so that users can easily know which field they should fill before submitting.

**Comment by sorahn** [comment]
There are only 3 optional fields, so maybe we just mark those instead.

**Comment by klion26** [comment]
thanks for the replay, mark the required or optional fields are both fine to me :)
