### ISSUE TITLE
Did not remove the old package when change the Category from `tools` to `language`

### ISSUE THREAD

**Issue by klion26** [sorahn/flink-ecosystem#58]
1. add a package tagged with `tools` https://flink-ecosystem-demo.flink-resources.org/packages/abcd
2. edit the package, change the Category from `tools` to `language`, the old package still exist.

**Comment by sorahn** [comment]
Right now the way the SQL is written the `categories` and `tags` all end up searched together.  So the `tools` category finds a partial match on your `toolsf` tag.

**Comment by sorahn** [comment]
@klion26 I have a fix for this, but after it is deployed it won't work right until an existing package is updated, or one is newly created.

**Comment by klion26** [comment]
@sorahn thanks for the quick fix, Seems your fix is in the backend, so why it would not work until an existing package is updated?

**Comment by sorahn** [comment]
>I'm just wondering here why can't we let it work for the existing package?

In order for the “find_in_set” MySQL command to work there can’t be any white space in the string between the commas. 

Previously I was saving the tags as “foo, bar, baz”. But in order for this to work they need to be saved as “foo,bar,baz”
