### ISSUE TITLE
Do we need to response when a user who did not log in click upvote

### ISSUE THREAD

**Issue by klion26** [sorahn/flink-ecosystem#60]
Currently, when a user who did not log in the website wants to upvote some package, he/she will receive no response. do we need to show something to him/her that upvote needs to log in?

**Comment by rmetzger** [comment]
That's a nice user experience improvement!
I'll add it to the backlog for v2

**Comment by rmetzger** [comment]
I would show a red tooltip asking people to log in

**Comment by sorahn** [comment]
fixed in #71
