### ISSUE TITLE
Time shows as a 24 hour am/pm combination

### ISSUE THREAD

**Issue by rmetzger** [sorahn/flink-ecosystem#63]
![image](https://user-images.githubusercontent.com/89049/61455693-8f72cd00-a964-11e9-8f26-fd197baeb1a8.png)

I guess that should be 2pm, instead of 14pm.

**Comment by sorahn** [comment]
Haha. nice.

Do you want am/pm or 24h?

**Comment by rmetzger** [comment]
am/pm :)
